### ISSUE TITLE
中文无法加粗

### ISSUE THREAD

**Issue by ghost** [ZJUGuoShuai/zh-academic#1]
中文无法加粗

**Comment by ZJUGuoShuai** [comment]
感谢，已经在 Commit [f29fd132ae](https://github.com/ZJUGuoShuai/zh-academic/commit/f29fd132aec5c6f7162f7ffbda7715ba0185b531) 解决。

**Comment by ZJUGuoShuai** [comment]
@yurjane 如果你测试正常，我将关闭此 issue。

**Comment by ghost** [comment]
测试正常:laughing:
