### ISSUE TITLE
Header 4 and Header 5 is of same size

### ISSUE THREAD

**Issue by Yeeef** [ZJUGuoShuai/zh-academic#2]
帅总 🐂🍺

![image](https://user-images.githubusercontent.com/34886010/59892948-b09bd880-940d-11e9-810d-00fb0dabe98d.png)

**Comment by ZJUGuoShuai** [comment]
之前他俩其实有点差别的，一个 1.2em，一个 1.1em，看起来确实差别不大。我现在改成和 GitHub README 一样，五级变小点，和六级一样，但是六级变灰色：

![image](https://user-images.githubusercontent.com/22856433/59971961-673bbc80-95b8-11e9-821d-eeade4b85a4b.png)
